### ISSUE TITLE
tListGrab file structure changes

### ISSUE THREAD

**Issue by sjstein** [sjstein/LynxSupport#8]
#### File contents:
1. For the column headers, I’d prefer ‘Tus’ (or ‘T_us’) and ‘ch’.  Avoid the special ‘(‘ character.
2. Leave out the final line in the CSV file.  Your corresponding info file tells me how many events were there, and I can count lines in this one if I want.  That final line only complicates the read because I no longer have two columns of numeric data throughout.

#### Naming:
1. The sequence number should maybe begin with _1 instead of _0?
2. Could we include the YYYYMMDD in the name?  Not a biggie, but this would be consistent with the other file names.
3. Instead of ‘events’, maybe ‘HPGelist’ or ‘HPGe’?
4. Can we change the file folder to either be 8-digit numeric YYYYMMDD or incorporate underscores rather than hyphens?  Again, for ease of processing, the fewer escape codes I have to generate the better.

**[Follow on discussions]** 

If I could have it all my way I would go with files named “HPGe_1549_20200829_01” (and 01, 02…) for the data and “logInfo_1549_20200829.txt” for the supporting file.  (Obviously that one doesn’t need a sequence number.)

Underscores are fine.  Hyphens and spaces aren’t terrible, but they add extra parsing work.  For the directory, I currently do the following:
MyScriptFolder
--Data
----20200820
----20200821

**Comment by sjstein** [comment]
re: Naming -> 3: 

> Instead of ‘events’, maybe ‘HPGelist’ or ‘HPGe’?

the file name is prepended with the info "File_Pre" portion of the config file so should be used to change the "events" qualifier to something more specific for the particular configuration ("HPGe" for example):

```
[LYNX]
...

[DETECTOR]
...

[DATA]
...
File_Pre = events
...
```

**Comment by dpeterson71** [comment]
I like this solution.  Allows the user to easily be more specific like "HPGe_scenario1" etc.
