### ISSUE TITLE
Archive calibration data 

### ISSUE THREAD

**Issue by sjstein** [sjstein/LynxSupport#9]
Add reading and archiving of calibration data in the logInfo file

**Comment by dpeterson71** [comment]
I would prefer a format of "Calibration: a b" where a and b are floats with the offset and slope.  Of course this would be preceded by the standard logging timestamp and "[INFO]" string.

**Comment by sjstein** [comment]
> I would prefer a format of "Calibration: a b" where a and b are floats with the offset and slope. Of course this would be preceded by the standard logging timestamp and "[INFO]" string.

FYI - as it stands now the timestamp and [INFO] string doesn't get written to that `logInfo` file - just stdout.
